#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
OUTPUT_PATH="${1:-$ROOT_DIR/ios/HoopsClips/HoopsClips/Config/LocalSecrets.xcconfig}"

required_vars=(
  HOOPS_DEVELOPMENT_TEAM
  HOOPS_REVENUECAT_API_KEY
  HOOPS_GOOGLE_CLIENT_ID
  HOOPS_GOOGLE_REVERSED_CLIENT_ID
  HOOPS_FIREBASE_AUTH_API_KEY
  HOOPS_PRIVACY_POLICY_URL
  HOOPS_TERMS_OF_SERVICE_URL
  HOOPS_SENTRY_DSN
)

missing_vars=()
for var_name in "${required_vars[@]}"; do
  if [[ -z "${!var_name:-}" ]]; then
    missing_vars+=("$var_name")
  fi
done

if (( ${#missing_vars[@]} > 0 )); then
  printf 'Missing required environment variables: %s\n' "${missing_vars[*]}" >&2
  exit 1
fi

xcconfig_escape() {
  local value="$1"
  value="${value//\/\///\$()/}"
  printf '%s' "$value"
}

mkdir -p "$(dirname "$OUTPUT_PATH")"

cat > "$OUTPUT_PATH" <<EOF
// Generated by ios/scripts/materialize_local_secrets.sh
HOOPS_DEVELOPMENT_TEAM = $(xcconfig_escape "${HOOPS_DEVELOPMENT_TEAM}")
HOOPS_REVENUECAT_API_KEY = $(xcconfig_escape "${HOOPS_REVENUECAT_API_KEY}")
HOOPS_GOOGLE_CLIENT_ID = $(xcconfig_escape "${HOOPS_GOOGLE_CLIENT_ID}")
HOOPS_GOOGLE_REVERSED_CLIENT_ID = $(xcconfig_escape "${HOOPS_GOOGLE_REVERSED_CLIENT_ID}")
HOOPS_FIREBASE_AUTH_API_KEY = $(xcconfig_escape "${HOOPS_FIREBASE_AUTH_API_KEY}")
HOOPS_PRIVACY_POLICY_URL = $(xcconfig_escape "${HOOPS_PRIVACY_POLICY_URL}")
HOOPS_TERMS_OF_SERVICE_URL = $(xcconfig_escape "${HOOPS_TERMS_OF_SERVICE_URL}")
HOOPS_SENTRY_DSN = $(xcconfig_escape "${HOOPS_SENTRY_DSN}")
EOF

printf 'Wrote %s\n' "$OUTPUT_PATH"
