import Foundation
import AVFoundation
import Vision
import Accelerate
import CoreImage
import CoreML

nonisolated final class FrameScore: @unchecked Sendable {
    let timestamp: Double
    let poseScore: Double
    let motionScore: Double
    let sceneScore: Double
    let poseCoverage: Double
    let brightness: Double
    let audioBurst: Double
    let observation: VNHumanBodyPoseObservation?
    let predictedAction: String?
    let actionConfidence: Double?

    init(
        timestamp: Double,
        poseScore: Double,
        motionScore: Double,
        sceneScore: Double,
        poseCoverage: Double,
        brightness: Double,
        audioBurst: Double,
        observation: VNHumanBodyPoseObservation?,
        predictedAction: String? = nil,
        actionConfidence: Double? = nil
    ) {
        self.timestamp = timestamp
        self.poseScore = poseScore
        self.motionScore = motionScore
        self.sceneScore = sceneScore
        self.poseCoverage = poseCoverage
        self.brightness = brightness
        self.audioBurst = audioBurst
        self.observation = observation
        self.predictedAction = predictedAction
        self.actionConfidence = actionConfidence
    }
}

struct AnalysisRunDiagnostics: Sendable {
    var frameCount: Int
    var effectiveWeights: AnalysisWeights
    var highThreshold: Double
    var lowThreshold: Double
    var recallPasses: Int
    var usedAudioFallback: Bool
    var usedMotionFallback: Bool
    var finalClipCount: Int

    init(
        frameCount: Int = 0,
        effectiveWeights: AnalysisWeights = AnalysisWeights(audio: 0.25, motion: 0.25, pose: 0.25, scene: 0.25),
        highThreshold: Double = 0.0,
        lowThreshold: Double = 0.0,
        recallPasses: Int = 0,
        usedAudioFallback: Bool = false,
        usedMotionFallback: Bool = false,
        finalClipCount: Int = 0
    ) {
        self.frameCount = frameCount
        self.effectiveWeights = effectiveWeights
        self.highThreshold = highThreshold
        self.lowThreshold = lowThreshold
        self.recallPasses = recallPasses
        self.usedAudioFallback = usedAudioFallback
        self.usedMotionFallback = usedMotionFallback
        self.finalClipCount = finalClipCount
    }
}

@Observable
@MainActor
final class VideoAnalysisService {
    var isAnalyzing = false
    var progress: Double = 0.0
    var statusMessage = ""
    var clips: [Clip] = []
    var lastRunDiagnostics: AnalysisRunDiagnostics?

    private var previousFrameBuffer: CVPixelBuffer?
    private var settings = AnalysisSettings()
    // Initialize the real model generated by Xcode
    private let actionClassifier = try? HoopsActionClassifier(configuration: MLModelConfiguration())

    func beginExternalAnalysis(status: String, progress: Double = 0.0) {
        isAnalyzing = true
        self.progress = progress
        statusMessage = status
        clips = []
    }

    func updateExternalAnalysis(progress: Double, status: String) {
        self.progress = progress
        statusMessage = status
    }

    func applyCloudAnalysis(_ result: CloudAnalysisResult) {
        clips = result.clips.map { $0.makeClip() }
        progress = 1.0
        statusMessage = "Found \(clips.count) highlight\(clips.count == 1 ? "" : "s")"
        isAnalyzing = false
    }

    func finishExternalAnalysis(with status: String) {
        statusMessage = status
        isAnalyzing = false
    }

    func analyze(url: URL, settings: AnalysisSettings) async {
        self.settings = settings
        isAnalyzing = true
        progress = 0.0
        clips = []
        lastRunDiagnostics = AnalysisRunDiagnostics()
        statusMessage = "Loading video..."
        
        let asset = AVURLAsset(url: url)

        guard let videoDuration = try? await asset.load(.duration) else {
            statusMessage = "Failed to load video"
            isAnalyzing = false
            return
        }

        let durationSeconds = CMTimeGetSeconds(videoDuration)

        statusMessage = "Extracting audio peaks..."
        let audioPeaks = await extractAudioPeaks(from: asset, duration: durationSeconds)
        progress = 0.15

        statusMessage = "Analyzing video frames..."
        let samplingFPS = min(max(settings.framesSampledPerSecond, 0.5), 12.0)
        let frameScores = await analyzeFrames(
            asset: asset,
            duration: durationSeconds,
            framesPerSecond: samplingFPS,
            settings: settings,
            audioPeaks: audioPeaks
        )
        progress = 0.75

        statusMessage = "Adapting scoring..."
        let effectiveWeights = computeAdaptiveWeights(frameScores: frameScores)
        lastRunDiagnostics?.frameCount = frameScores.count
        lastRunDiagnostics?.effectiveWeights = effectiveWeights

        statusMessage = "Detecting highlights..."
        var rawClips = buildClips(
            frameScores: frameScores,
            audioPeaks: audioPeaks,
            duration: durationSeconds,
            weights: effectiveWeights
        )

        // Recall recovery pass: lower thresholds once more before hard fallbacks.
        if rawClips.isEmpty {
            statusMessage = "Refining detection..."
            rawClips = buildClips(
                frameScores: frameScores,
                audioPeaks: audioPeaks,
                duration: durationSeconds,
                weights: effectiveWeights,
                thresholdOverride: max(0.22, settings.confidenceThreshold * 0.72)
            )
            if rawClips.isEmpty {
                statusMessage = "Applying fallback detection..."
                if audioPeaks.max() ?? 0 > 0.25 {
                    rawClips = buildAudioOnlyClips(audioPeaks: audioPeaks, duration: durationSeconds)
                    if !rawClips.isEmpty {
                        lastRunDiagnostics?.usedAudioFallback = true
                    }
                }
                if rawClips.isEmpty {
                    rawClips = buildMotionOnlyClips(frameScores: frameScores, duration: durationSeconds)
                    if !rawClips.isEmpty {
                        lastRunDiagnostics?.usedMotionFallback = true
                    }
                }
            }
        }

        progress = 0.90

        statusMessage = "Classifying actions..."
        clips = classifyActions(clips: rawClips, frameScores: frameScores)
        lastRunDiagnostics?.finalClipCount = clips.count
        progress = 1.0

        statusMessage = "Found \(clips.count) highlight\(clips.count == 1 ? "" : "s")"
        isAnalyzing = false
    }

    private func extractAudioPeaks(from asset: AVURLAsset, duration: Double) async -> [Double] {
        let sampleCount = Int(duration * 10)
        var peaks = [Double](repeating: 0.0, count: max(sampleCount, 1))

        guard let audioTrack = try? await asset.loadTracks(withMediaType: .audio).first else {
            return peaks
        }

        do {
            let reader = try AVAssetReader(asset: asset)
            let outputSettings: [String: Any] = [
                AVFormatIDKey: kAudioFormatLinearPCM,
                AVLinearPCMBitDepthKey: 16,
                AVLinearPCMIsFloatKey: false,
                AVLinearPCMIsBigEndianKey: false,
                AVLinearPCMIsNonInterleaved: false,
                AVSampleRateKey: 44100,
                AVNumberOfChannelsKey: 1
            ]

            let trackOutput = AVAssetReaderTrackOutput(track: audioTrack, outputSettings: outputSettings)
            reader.add(trackOutput)
            reader.startReading()

            var allSamples: [Int16] = []
            while let sampleBuffer = trackOutput.copyNextSampleBuffer() {
                guard let blockBuffer = CMSampleBufferGetDataBuffer(sampleBuffer) else { continue }
                let length = CMBlockBufferGetDataLength(blockBuffer)
                var data = Data(count: length)
                data.withUnsafeMutableBytes { rawBuffer in
                    guard let ptr = rawBuffer.baseAddress else { return }
                    CMBlockBufferCopyDataBytes(blockBuffer, atOffset: 0, dataLength: length, destination: ptr)
                }
                let samples = data.withUnsafeBytes { rawBuffer in
                    Array(rawBuffer.bindMemory(to: Int16.self))
                }
                allSamples.append(contentsOf: samples)
            }

            let samplesPerBucket = max(allSamples.count / sampleCount, 1)
            for i in 0..<min(sampleCount, allSamples.count / max(samplesPerBucket, 1)) {
                let start = i * samplesPerBucket
                let end = min(start + samplesPerBucket, allSamples.count)
                let slice = allSamples[start..<end]
                let rms = sqrt(slice.reduce(0.0) { $0 + Double($1) * Double($1) } / Double(slice.count))
                peaks[i] = rms / 32768.0
            }
        } catch {
            // Audio extraction failed, return zeros
        }

        let maxPeak = peaks.max() ?? 1.0
        if maxPeak > 0 {
            peaks = peaks.map { $0 / maxPeak }
        }

        return peaks
    }

    private nonisolated func analyzeFrames(
        asset: AVURLAsset,
        duration: Double,
        framesPerSecond fps: Double,
        settings: AnalysisSettings,
        audioPeaks: [Double]
    ) async -> [FrameScore] {
        let totalFrames = max(Int(ceil(max(duration, 0) * fps)), 1)
        var scores: [FrameScore] = []

        let generator = AVAssetImageGenerator(asset: asset)
        generator.appliesPreferredTrackTransform = true
        generator.requestedTimeToleranceBefore = CMTime(seconds: 0.1, preferredTimescale: 600)
        generator.requestedTimeToleranceAfter = CMTime(seconds: 0.1, preferredTimescale: 600)
        generator.maximumSize = CGSize(width: 640, height: 360)

        var previousImage: CGImage?
        
        // Sliding window for action classification
        var poseWindow: [PoseFrame] = []
        
        for i in 0..<totalFrames {
            let time = Double(i) / fps
            let cmTime = CMTime(seconds: time, preferredTimescale: 600)

            do {
                let (image, _) = try await generator.image(at: cmTime)

                let (poseScore, observation) = await analyzePose(image: image)
                let motionScore = analyzeMotion(current: image, previous: previousImage)
                let sceneScore = analyzeScene(image: image)
                let poseCoverage = calculatePoseCoverage(observation)
                let audioIndex = max(0, min(audioPeaks.count - 1, Int(time * 10.0)))
                let audioBurst = AnalysisQualityTuning.localAverage(values: audioPeaks, center: audioIndex, radius: 2)
                
                // Update sliding window
                let poseFrame = convertToPoseFrame(observation)
                poseWindow.append(poseFrame)
                if poseWindow.count > settings.mlWindowSize {
                    poseWindow.removeFirst()
                }
                
                // Predict action if window is full
                var predictedAction: String?
                var actionConfidence: Double?
                
                if poseWindow.count == settings.mlWindowSize {
                    if let prediction = await predictAction(from: poseWindow) {
                        predictedAction = prediction.label
                        actionConfidence = prediction.confidence
                    }
                }

                let frame = FrameScore(
                    timestamp: time,
                    poseScore: poseScore,
                    motionScore: motionScore,
                    sceneScore: sceneScore,
                    poseCoverage: poseCoverage,
                    brightness: sceneScore,
                    audioBurst: audioBurst,
                    observation: observation,
                    predictedAction: predictedAction,
                    actionConfidence: actionConfidence
                )
                scores.append(frame)
                previousImage = image

                if i % 10 == 0 || i == totalFrames - 1 {
                    let progressValue = 0.15 + (Double(i + 1) / Double(totalFrames)) * 0.60
                    await MainActor.run { self.progress = progressValue }
                }
            } catch {
                continue
            }
        }

        return scores
    }
    
    private nonisolated func convertToPoseFrame(_ observation: VNHumanBodyPoseObservation?) -> PoseFrame {
        guard let obs = observation else {
            return PoseFrame(points: [:])
        }
        
        // Reuse PoseInputBuilder.convert logic for single frame
        // Since convert expects array, we can use it or just replicate logic
        // Replicating logic is safer to avoid creating array overhead
        var points: [VNHumanBodyPoseObservation.JointName: PosePoint] = [:]
        
        for joint in PoseInputBuilder.jointNames {
            if let recognized = try? obs.recognizedPoint(joint), recognized.confidence > 0 {
                points[joint] = PosePoint(
                    x: recognized.location.x,
                    y: recognized.location.y,
                    confidence: Double(recognized.confidence)
                )
            }
        }
        return PoseFrame(points: points)
    }

    private nonisolated func calculatePoseCoverage(_ observation: VNHumanBodyPoseObservation?) -> Double {
        guard let obs = observation else { return 0.0 }
        var detectedCount = 0
        for joint in PoseInputBuilder.jointNames {
            if let point = try? obs.recognizedPoint(joint), point.confidence > 0.15 {
                detectedCount += 1
            }
        }
        guard !PoseInputBuilder.jointNames.isEmpty else { return 0.0 }
        return Double(detectedCount) / Double(PoseInputBuilder.jointNames.count)
    }

    private nonisolated func analyzePose(image: CGImage) async -> (Double, VNHumanBodyPoseObservation?) {
        let request = VNDetectHumanBodyPoseRequest()
        let handler = VNImageRequestHandler(cgImage: image, options: [:])

        do {
            try handler.perform([request])

            guard let observations = request.results, !observations.isEmpty else {
                return (0.0, nil)
            }

            var maxScore = 0.0
            var bestObservation: VNHumanBodyPoseObservation?

            for observation in observations {
                var score = 0.3

                if let rightWrist = try? observation.recognizedPoint(.rightWrist),
                   let rightShoulder = try? observation.recognizedPoint(.rightShoulder),
                   rightWrist.confidence > 0.3 && rightShoulder.confidence > 0.3 {
                    if rightWrist.location.y > rightShoulder.location.y {
                        score += 0.3
                    }
                }

                if let leftWrist = try? observation.recognizedPoint(.leftWrist),
                   let leftShoulder = try? observation.recognizedPoint(.leftShoulder),
                   leftWrist.confidence > 0.3 && leftShoulder.confidence > 0.3 {
                    if leftWrist.location.y > leftShoulder.location.y {
                        score += 0.2
                    }
                }

                if let rightAnkle = try? observation.recognizedPoint(.rightAnkle),
                   let rightHip = try? observation.recognizedPoint(.rightHip),
                   rightAnkle.confidence > 0.3 && rightHip.confidence > 0.3 {
                    let legExtension = abs(rightAnkle.location.y - rightHip.location.y)
                    if legExtension > 0.4 {
                        score += 0.2
                    }
                }

                let jointConfidences = [
                    try? observation.recognizedPoint(.nose),
                    try? observation.recognizedPoint(.neck),
                    try? observation.recognizedPoint(.rightShoulder),
                    try? observation.recognizedPoint(.leftShoulder),
                    try? observation.recognizedPoint(.rightElbow),
                    try? observation.recognizedPoint(.leftElbow),
                    try? observation.recognizedPoint(.rightWrist),
                    try? observation.recognizedPoint(.leftWrist)
                ].compactMap { $0?.confidence }

                let avgConfidence = jointConfidences.isEmpty ? 0 : Double(jointConfidences.reduce(0, +)) / Double(jointConfidences.count)
                score *= Double(avgConfidence)

                if score > maxScore {
                    maxScore = score
                    bestObservation = observation
                }
            }

            if observations.count >= 2 {
                maxScore = min(maxScore * 1.2, 1.0)
            }

            return (min(maxScore, 1.0), bestObservation)
        } catch {
            return (0.0, nil)
        }
    }

    private nonisolated func analyzeMotion(current: CGImage, previous: CGImage?) -> Double {
        guard let previous = previous else { return 0.0 }

        let width = min(current.width, previous.width)
        let height = min(current.height, previous.height)
        guard width > 0 && height > 0 else { return 0.0 }

        let colorSpace = CGColorSpaceCreateDeviceGray()
        let bytesPerRow = width
        let totalPixels = width * height

        var currentPixels = [UInt8](repeating: 0, count: totalPixels)
        var previousPixels = [UInt8](repeating: 0, count: totalPixels)

        guard let currentCtx = CGContext(
            data: &currentPixels, width: width, height: height,
            bitsPerComponent: 8, bytesPerRow: bytesPerRow,
            space: colorSpace, bitmapInfo: CGImageAlphaInfo.none.rawValue
        ) else { return 0.0 }

        guard let previousCtx = CGContext(
            data: &previousPixels, width: width, height: height,
            bitsPerComponent: 8, bytesPerRow: bytesPerRow,
            space: colorSpace, bitmapInfo: CGImageAlphaInfo.none.rawValue
        ) else { return 0.0 }

        currentCtx.draw(current, in: CGRect(x: 0, y: 0, width: width, height: height))
        previousCtx.draw(previous, in: CGRect(x: 0, y: 0, width: width, height: height))

        var totalDiff: Double = 0
        let sampleStep = max(totalPixels / 10000, 1)
        var sampledCount = 0

        for i in stride(from: 0, to: totalPixels, by: sampleStep) {
            let diff = abs(Int(currentPixels[i]) - Int(previousPixels[i]))
            totalDiff += Double(diff)
            sampledCount += 1
        }

        let avgDiff = sampledCount > 0 ? totalDiff / Double(sampledCount) : 0
        let normalized = min(avgDiff / 40.0, 1.0)
        return normalized
    }

    private nonisolated func analyzeScene(image: CGImage) -> Double {
        let width = image.width
        let height = image.height
        guard width > 0 && height > 0 else { return 0.0 }

        let colorSpace = CGColorSpaceCreateDeviceRGB()
        let bytesPerPixel = 4
        let bytesPerRow = width * bytesPerPixel
        let totalPixels = width * height
        var pixels = [UInt8](repeating: 0, count: totalPixels * bytesPerPixel)

        guard let context = CGContext(
            data: &pixels, width: width, height: height,
            bitsPerComponent: 8, bytesPerRow: bytesPerRow,
            space: colorSpace, bitmapInfo: CGImageAlphaInfo.premultipliedLast.rawValue
        ) else { return 0.0 }

        context.draw(image, in: CGRect(x: 0, y: 0, width: width, height: height))

        var brightPixelCount = 0
        let sampleStep = max(totalPixels / 5000, 1)
        var sampledCount = 0

        for i in stride(from: 0, to: totalPixels, by: sampleStep) {
            let offset = i * bytesPerPixel
            let r = Double(pixels[offset])
            let g = Double(pixels[offset + 1])
            let b = Double(pixels[offset + 2])
            let brightness = (r + g + b) / (3.0 * 255.0)
            if brightness > 0.7 {
                brightPixelCount += 1
            }
            sampledCount += 1
        }

        let brightRatio = sampledCount > 0 ? Double(brightPixelCount) / Double(sampledCount) : 0
        return min(brightRatio * 2.0, 1.0)
    }

    private func computeAdaptiveWeights(frameScores: [FrameScore]) -> AnalysisWeights {
        let base = AnalysisWeights(
            audio: settings.audioWeight,
            motion: settings.motionWeight,
            pose: settings.poseWeight,
            scene: settings.sceneWeight
        )
        guard !frameScores.isEmpty else { return AnalysisQualityTuning.normalized(base) }

        let avgPoseCoverage = frameScores.reduce(0.0) { $0 + $1.poseCoverage } / Double(frameScores.count)
        let avgBrightness = frameScores.reduce(0.0) { $0 + $1.brightness } / Double(frameScores.count)
        return AnalysisQualityTuning.adaptiveWeights(
            base: base,
            averagePoseCoverage: avgPoseCoverage,
            averageBrightness: avgBrightness
        )
    }

    private func buildClips(
        frameScores: [FrameScore],
        audioPeaks: [Double],
        duration: Double,
        weights: AnalysisWeights,
        thresholdOverride: Double? = nil
    ) -> [Clip] {
        guard !frameScores.isEmpty else { return [] }

        var timeline: [ScorePoint] = []
        timeline.reserveCapacity(frameScores.count)

        for frame in frameScores {
            let audioIndex = max(0, min(audioPeaks.count - 1, Int(frame.timestamp * 10)))
            let audioScore = audioPeaks.isEmpty ? 0.0 : audioPeaks[audioIndex]
            let boostedAudio = 0.65 * audioScore + 0.35 * frame.audioBurst

            let combined = weights.audio * boostedAudio
                + weights.motion * frame.motionScore
                + weights.pose * frame.poseScore
                + weights.scene * frame.sceneScore
            timeline.append(ScorePoint(time: frame.timestamp, score: min(max(combined, 0), 1)))
        }

        let smoothingRadius = max(2, settings.scoreSmoothingWindow + 1)
        let smoothed = AnalysisQualityTuning.triangularSmooth(points: timeline, radius: smoothingRadius)

        let baseThreshold = min(max(thresholdOverride ?? settings.confidenceThreshold, 0.12), 0.92)
        var highThreshold = min(max(baseThreshold + 0.08, 0.18), 0.95)
        var lowThreshold = min(max(baseThreshold - 0.08, 0.08), highThreshold - 0.03)
        let minDuration = max(1.2, settings.minClipDuration * (settings.preferKeepUncertain ? 0.75 : 1.0))
        let mergeGap = max(0.8, settings.clipPadding * 0.7)

        var windows = AnalysisQualityTuning.segmentWithHysteresis(
            points: smoothed,
            highThreshold: highThreshold,
            lowThreshold: lowThreshold,
            minDuration: minDuration,
            maxDuration: settings.maxClipDuration,
            padding: settings.clipPadding,
            durationLimit: duration,
            mergeGap: mergeGap
        )

        let targetCount = recommendedMinimumClipCount(duration: duration)
        var recallPasses = 0
        while windows.count < targetCount && recallPasses < 2 {
            recallPasses += 1
            highThreshold = max(0.12, highThreshold * 0.92)
            lowThreshold = max(0.06, min(highThreshold - 0.02, lowThreshold * 0.90))
            windows = AnalysisQualityTuning.segmentWithHysteresis(
                points: smoothed,
                highThreshold: highThreshold,
                lowThreshold: lowThreshold,
                minDuration: minDuration * 0.9,
                maxDuration: settings.maxClipDuration,
                padding: settings.clipPadding,
                durationLimit: duration,
                mergeGap: mergeGap
            )
        }

        lastRunDiagnostics?.highThreshold = highThreshold
        lastRunDiagnostics?.lowThreshold = lowThreshold
        lastRunDiagnostics?.recallPasses = recallPasses

        let mappedClips = windows.map { window in
            let midpoint = (window.start + window.end) / 2.0
            let audioIndex = max(0, min(audioPeaks.count - 1, Int(midpoint * 10)))
            let localAudio = audioPeaks.isEmpty ? 0.0 : AnalysisQualityTuning.localAverage(values: audioPeaks, center: audioIndex, radius: 2)

            let framesInRange = frameScores.filter { $0.timestamp >= window.start && $0.timestamp <= window.end }
            let avgMotion = framesInRange.isEmpty ? 0.0 : framesInRange.reduce(0.0) { $0 + $1.motionScore } / Double(framesInRange.count)
            let avgPose = framesInRange.isEmpty ? 0.0 : framesInRange.reduce(0.0) { $0 + $1.poseScore } / Double(framesInRange.count)

            let ranking = (window.peakScore * 0.45)
                + (window.meanScore * 0.20)
                + (avgMotion * 0.15)
                + (avgPose * 0.10)
                + (localAudio * 0.10)
            let confidenceFloor = settings.preferKeepUncertain ? 0.50 : 0.38
            let confidence = min(1.0, max(ranking, confidenceFloor))
            let keepThreshold = settings.preferKeepUncertain ? 0.30 : 0.38

            return Clip(
                startTime: window.start,
                endTime: window.end,
                confidence: confidence,
                isKept: confidence >= keepThreshold,
                audioScore: localAudio,
                visualScore: avgPose,
                motionScore: avgMotion,
                combinedScore: ranking
            )
        }

        let maxClipCount = recommendedMaximumClipCount(duration: duration)
        if mappedClips.count <= maxClipCount {
            return mappedClips.sorted { $0.startTime < $1.startTime }
        }

        let topByScore = mappedClips
            .sorted { lhs, rhs in
                if lhs.combinedScore == rhs.combinedScore {
                    return lhs.startTime < rhs.startTime
                }
                return lhs.combinedScore > rhs.combinedScore
            }
            .prefix(maxClipCount)

        return topByScore.sorted { $0.startTime < $1.startTime }
    }

    private func recommendedMinimumClipCount(duration: Double) -> Int {
        if duration < 45 { return 1 }
        if duration < 120 { return 2 }
        if duration < 240 { return 3 }
        return 4
    }

    private func recommendedMaximumClipCount(duration: Double) -> Int {
        if duration < 60 { return 6 }
        if duration < 180 { return 12 }
        return 16
    }

    private func buildAudioOnlyClips(audioPeaks: [Double], duration: Double) -> [Clip] {
        var clipRanges: [(start: Double, end: Double, peakScore: Double)] = []
        // Use a much lower threshold for audio fallback - even 20% of max is better than nothing
        let maxPeak = audioPeaks.max() ?? 1.0
        let threshold = 0.3 * maxPeak
        
        for (index, peak) in audioPeaks.enumerated() {
            if peak > threshold {
                let time = Double(index) / 10.0 // Audio peaks are 10 per second
                // Merge with previous if close
                if let last = clipRanges.last, time - last.end < 2.0 {
                    clipRanges[clipRanges.count - 1] = (start: last.start, end: time + 1.5, peakScore: max(last.peakScore, peak))
                } else {
                    clipRanges.append((start: max(0, time - 1.5), end: min(duration, time + 1.5), peakScore: peak))
                }
            }
        }
        
        // If we still found nothing with 0.3 threshold, try even lower (0.15) just to generate SOMETHING
        if clipRanges.isEmpty && maxPeak > 0.05 {
             let lowThreshold = 0.15 * maxPeak
             for (index, peak) in audioPeaks.enumerated() {
                if peak > lowThreshold {
                    let time = Double(index) / 10.0
                    if let last = clipRanges.last, time - last.end < 2.0 {
                        clipRanges[clipRanges.count - 1] = (start: last.start, end: time + 1.5, peakScore: max(last.peakScore, peak))
                    } else {
                        clipRanges.append((start: max(0, time - 1.5), end: min(duration, time + 1.5), peakScore: peak))
                    }
                }
            }
        }
        
        return clipRanges.map { range in
            Clip(
                startTime: range.start,
                endTime: range.end,
                confidence: 0.42,
                isKept: true, // Auto-keep since it's a fallback
                label: "Action", // Generic label
                audioScore: range.peakScore,
                visualScore: 0.0,
                motionScore: 0.0,
                combinedScore: range.peakScore,
                detectionMethod: .heuristic
            )
        }
    }

    private func buildMotionOnlyClips(frameScores: [FrameScore], duration: Double) -> [Clip] {
        guard !frameScores.isEmpty else { return [] }

        let peakMotion = frameScores.map(\.motionScore).max() ?? 0.0
        guard peakMotion > 0.20 else { return [] }

        let threshold = max(0.30, peakMotion * 0.62)
        var windows: [SegmentedClipWindow] = []
        var currentStart: Double?
        var currentEnd: Double?
        var currentPeak = 0.0
        var currentSum = 0.0
        var currentCount = 0

        for frame in frameScores {
            if frame.motionScore >= threshold {
                if currentStart == nil {
                    currentStart = frame.timestamp
                    currentEnd = frame.timestamp
                    currentPeak = frame.motionScore
                    currentSum = frame.motionScore
                    currentCount = 1
                } else {
                    currentEnd = frame.timestamp
                    currentPeak = max(currentPeak, frame.motionScore)
                    currentSum += frame.motionScore
                    currentCount += 1
                }
            } else if let start = currentStart, let end = currentEnd {
                if end - start >= max(1.2, settings.minClipDuration * 0.65) {
                    windows.append(
                        SegmentedClipWindow(
                            start: max(0, start - settings.clipPadding),
                            end: min(duration, min(start + settings.maxClipDuration, end + settings.clipPadding)),
                            peakScore: currentPeak,
                            meanScore: currentCount > 0 ? currentSum / Double(currentCount) : currentPeak
                        )
                    )
                }
                currentStart = nil
                currentEnd = nil
                currentPeak = 0.0
                currentSum = 0.0
                currentCount = 0
            }
        }

        if let start = currentStart, let end = currentEnd, end - start >= max(1.2, settings.minClipDuration * 0.65) {
            windows.append(
                SegmentedClipWindow(
                    start: max(0, start - settings.clipPadding),
                    end: min(duration, min(start + settings.maxClipDuration, end + settings.clipPadding)),
                    peakScore: currentPeak,
                    meanScore: currentCount > 0 ? currentSum / Double(currentCount) : currentPeak
                )
            )
        }

        return windows.map { window in
            Clip(
                startTime: window.start,
                endTime: window.end,
                confidence: min(1.0, max(0.38, (window.peakScore * 0.5 + window.meanScore * 0.5))),
                isKept: true,
                label: "Action",
                audioScore: 0.0,
                visualScore: 0.0,
                motionScore: window.peakScore,
                combinedScore: window.meanScore,
                detectionMethod: .heuristic
            )
        }
    }
    
    func predictAction(from poseWindow: [PoseFrame]) async -> (label: String, confidence: Double)? {
        // Run prediction on MainActor because actionClassifier is actor-isolated or non-sendable usually
        // But here it is a class property of MainActor class.
        // Wait, actionClassifier logic might need to run on same actor as init?
        // Let's assume actionClassifier is thread-safe or we access it on MainActor (since this func is on MainActor via class)
        
        guard let model = actionClassifier else { return nil }
        guard !poseWindow.isEmpty else { return nil }
        
        // buildInput is static and safe
        guard let multiArray = PoseInputBuilder.buildInput(from: poseWindow) else {
            return nil
        }
        
        do {
            // Predict
            // Note: prediction method name is `prediction(pose_window: MLMultiArray)`
            let output = try model.prediction(pose_window: multiArray)
            let label = output.label
            let confidence = output.labelProbability[label] ?? 0.0
            return (label, confidence)
        } catch {
            print("Prediction error: \(error)")
            return nil
        }
    }

    func classifyActions(clips: [Clip], frameScores: [FrameScore]) -> [Clip] {
        return clips.map { clip in
            var classified = clip

            let framesInClip = frameScores.filter { $0.timestamp >= clip.startTime && $0.timestamp <= clip.endTime }
            let maxMotion = framesInClip.map(\.motionScore).max() ?? 0
            let maxPose = framesInClip.map(\.poseScore).max() ?? 0
            let avgMotion = framesInClip.isEmpty ? 0 : framesInClip.reduce(0.0) { $0 + $1.motionScore } / Double(framesInClip.count)
            let avgPose = framesInClip.isEmpty ? 0 : framesInClip.reduce(0.0) { $0 + $1.poseScore } / Double(framesInClip.count)
            let avgAudioBurst = framesInClip.isEmpty ? clip.audioScore : framesInClip.reduce(0.0) { $0 + $1.audioBurst } / Double(framesInClip.count)
            
            // 1. Try weighted ML voting first.
            var votes: [PredictionVote] = []
            let minConfidenceFloor = 0.35
            for (index, frame) in framesInClip.enumerated() {
                guard let label = frame.predictedAction,
                      let confidence = frame.actionConfidence,
                      confidence >= minConfidenceFloor else {
                    continue
                }
                let recencyWeight = framesInClip.count <= 1 ? 1.0 : 0.75 + (Double(index) / Double(framesInClip.count - 1)) * 0.5
                votes.append(
                    PredictionVote(
                        label: label,
                        confidence: confidence,
                        recencyWeight: recencyWeight
                    )
                )
            }

            if let bestLabel = AnalysisQualityTuning.weightedWinningLabel(
                votes: votes,
                minCount: settings.minMLPredictionCount,
                minMargin: 0.18
            ) {
                if let action = HighlightAction(rawValue: bestLabel)
                    ?? HighlightAction.allCases.first(where: { $0.rawValue.localizedCaseInsensitiveCompare(bestLabel) == .orderedSame }),
                   action != .unknown {
                    classified.action = action
                    classified.label = action.rawValue
                    classified.detectionMethod = .ml
                    if action == .dunk {
                        classified.isSlowMotionEnabled = true
                    }
                    return classified
                }
            }

            // 2. Fallback Heuristics
            classified.detectionMethod = .heuristic
            
            if maxPose > 0.56 && maxMotion > 0.48 {
                if max(clip.audioScore, avgAudioBurst) > 0.52 {
                    classified.action = .dunk
                } else {
                    classified.action = .posterize
                }
            } else if avgPose > 0.42 && avgMotion > 0.38 {
                if clip.duration < 4.2 {
                    classified.action = .layup
                } else {
                    classified.action = .madeShot
                }
            } else if maxMotion > 0.62 {
                classified.action = .fastBreak
            } else if avgMotion > 0.44 && maxPose > 0.24 {
                if max(clip.audioScore, avgAudioBurst) > 0.38 {
                    classified.action = .threePointer
                } else {
                    classified.action = .steal
                }
            } else if maxPose > 0.34 {
                classified.action = .block
            } else if max(clip.audioScore, avgAudioBurst) > 0.50 {
                classified.action = .madeShot
            } else {
                classified.action = .unknown
            }

            classified.label = classified.action.rawValue
            return classified
        }
    }
}
