#!/usr/bin/env python3
from __future__ import annotations

import argparse
import hashlib
import json
import os
import subprocess
import sys
from pathlib import Path
from typing import Any


class SmokeSequenceError(Exception):
    def __init__(self, message: str, payload: dict[str, Any] | None = None) -> None:
        super().__init__(message)
        self.payload = payload or {}


def main() -> int:
    args = parse_args()
    try:
        result = run_sequence(args)
        assert_shareable_evidence(result)
        if args.evidence_path:
            write_evidence(args.evidence_path, result)
            result["evidenceWritten"] = True
            result["evidencePathHash"] = stable_hash(str(args.evidence_path))
            assert_shareable_evidence(result)
        print(json.dumps(result, indent=2, sort_keys=True))
        return 0
    except SmokeSequenceError as error:
        payload = {
            "status": "fail",
            "error": str(error),
            **error.payload,
            "privacy": "no_secrets_no_presigned_urls_no_object_keys",
        }
        print(json.dumps(payload, indent=2, sort_keys=True), file=sys.stderr)
        return 1


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Run the full HoopClips resumable-upload interruption proof sequence. "
            "Output is sanitized and does not include presigned URLs, object keys, upload IDs, or raw local paths."
        )
    )
    parser.add_argument("--worker-url", default=os.getenv("WORKER_BASE_URL"))
    parser.add_argument("--file", dest="file_path", type=Path)
    parser.add_argument("--state-path", type=Path, default=Path("artifacts/resumable_upload_interrupt_state.json"))
    parser.add_argument("--evidence-path", type=Path, default=Path("artifacts/resumable_upload_interrupt_sequence_evidence.json"))
    parser.add_argument("--generate-test-file-mb", type=int, default=0)
    parser.add_argument("--auto-generate-test-file", action="store_true")
    parser.add_argument("--timeout-seconds", type=float, default=float(os.getenv("HOOPS_UPLOAD_SMOKE_TIMEOUT_SECONDS", "60")))
    parser.add_argument("--install-id", default=os.getenv("HOOPS_UPLOAD_SMOKE_INSTALL_ID", "resumable-upload-smoke-install"))
    parser.add_argument("--app-version", default=os.getenv("HOOPS_UPLOAD_SMOKE_APP_VERSION", "resumable-upload-smoke"))
    parser.add_argument("--analysis-version", default=os.getenv("HOOPS_UPLOAD_SMOKE_ANALYSIS_VERSION", "resumable-upload-smoke"))
    parser.add_argument("--duration-seconds", type=float, default=float(os.getenv("HOOPS_UPLOAD_SMOKE_DURATION_SECONDS", "60")))
    parser.add_argument("--content-type")
    parser.add_argument(
        "--replace-existing-state",
        action="store_true",
        help=(
            "Delete an existing private resume state file before starting the sequence. "
            "Use this for repeat proof runs so old job/upload identifiers cannot affect new evidence."
        ),
    )
    args = parser.parse_args()

    if not args.worker_url:
        raise SmokeSequenceError("WORKER_BASE_URL or --worker-url is required.")
    if args.timeout_seconds <= 0:
        raise SmokeSequenceError("Timeout must be positive.", {"timeoutSeconds": args.timeout_seconds})
    if args.generate_test_file_mb < 0:
        raise SmokeSequenceError("--generate-test-file-mb must be zero or positive.")
    if not args.file_path and args.generate_test_file_mb <= 0:
        args.auto_generate_test_file = True
    if args.state_path.exists():
        if not args.replace_existing_state:
            raise SmokeSequenceError(
                "Resume state file already exists. Pass --replace-existing-state to start a fresh sequence.",
                {
                    "statePathHash": stable_hash(str(args.state_path)),
                    "privacy": "state_path_is_hashed_no_local_path_printed",
                },
            )
        args.state_path.unlink()
    return args


def run_sequence(args: argparse.Namespace) -> dict[str, Any]:
    first = run_smoke_step(args, ["--mode", "interrupt-after-first"], include_source=True)
    second = run_smoke_step(args, ["--mode", "resume", "--stop-after-new-parts", "1"], include_source=False)
    final = run_smoke_step(args, ["--mode", "resume", "--verify-duplicate-complete"], include_source=False)

    status = "pass" if (
        first.get("status") == "interrupted"
        and second.get("status") == "interrupted"
        and final.get("status") == "pass"
        and final.get("interruptionProven") is True
        and final.get("duplicateCompleteProven") is True
    ) else "fail"

    result = {
        "status": status,
        "mode": "sequence",
        "worker": final.get("worker") or first.get("worker") or "unknown",
        "statePathHash": stable_hash(str(args.state_path)),
        "sourcePathHash": stable_hash(str(args.file_path.resolve())) if args.file_path else None,
        "autoGeneratedSource": not bool(args.file_path),
        "startedFromFreshState": True,
        "firstPhase": first,
        "secondPhase": second,
        "finalPhase": final,
        "partCount": final.get("partCount") or second.get("partCount") or first.get("partCount"),
        "completedParts": final.get("completedParts"),
        "interruptionProven": final.get("interruptionProven") is True,
        "duplicateCompleteProven": final.get("duplicateCompleteProven") is True,
        "privacy": "no_secrets_no_presigned_urls_no_object_keys_no_raw_local_paths",
    }
    return sanitize_for_shareable_evidence(result)


def run_smoke_step(args: argparse.Namespace, step_args: list[str], include_source: bool) -> dict[str, Any]:
    script_path = Path(__file__).with_name("resumable_upload_interrupt_smoke.py")
    command = [
        sys.executable,
        str(script_path),
        "--worker-url",
        str(args.worker_url),
        "--state-path",
        str(args.state_path),
        "--timeout-seconds",
        str(args.timeout_seconds),
        "--install-id",
        str(args.install_id),
        "--app-version",
        str(args.app_version),
        "--analysis-version",
        str(args.analysis_version),
        "--duration-seconds",
        str(args.duration_seconds),
        *step_args,
    ]
    if args.content_type:
        command.extend(["--content-type", str(args.content_type)])
    if include_source:
        if args.file_path:
            command.extend(["--file", str(args.file_path)])
        elif args.generate_test_file_mb > 0:
            command.extend(["--generate-test-file-mb", str(args.generate_test_file_mb)])
        else:
            command.append("--auto-generate-test-file")

    completed = subprocess.run(command, capture_output=True, text=True, check=False)
    if completed.returncode != 0:
        raise SmokeSequenceError(
            "Resumable upload smoke step failed.",
            {
                "returnCode": completed.returncode,
                "step": " ".join(step_args),
                "stderrSummary": summarize_text(completed.stderr),
            },
        )
    try:
        decoded = json.loads(completed.stdout)
    except json.JSONDecodeError as error:
        raise SmokeSequenceError(
            "Resumable upload smoke step returned invalid JSON.",
            {"step": " ".join(step_args)},
        ) from error
    if not isinstance(decoded, dict):
        raise SmokeSequenceError("Resumable upload smoke step returned non-object JSON.", {"step": " ".join(step_args)})
    return sanitize_for_shareable_evidence(decoded)


def write_evidence(evidence_path: Path, result: dict[str, Any]) -> None:
    evidence_path.parent.mkdir(parents=True, exist_ok=True)
    evidence = sanitize_for_shareable_evidence(result)
    assert_shareable_evidence(evidence)
    evidence_path.write_text(json.dumps(evidence, indent=2, sort_keys=True), encoding="utf-8")


def sanitize_for_shareable_evidence(value: Any) -> Any:
    if isinstance(value, dict):
        sanitized: dict[str, Any] = {}
        for key, item in value.items():
            if key in {"statePath", "sourcePath", "jobId", "uploadId", "sourceObjectKey", "uploadUrl"}:
                sanitized[f"{key}Hash"] = stable_hash(str(item))
            elif key in {"uploadHeaders"}:
                sanitized[key] = "[redacted]"
            else:
                sanitized[key] = sanitize_for_shareable_evidence(item)
        return sanitized
    if isinstance(value, list):
        return [sanitize_for_shareable_evidence(item) for item in value]
    return value


def assert_shareable_evidence(value: Any) -> None:
    leaks = find_shareable_evidence_leaks(value)
    if leaks:
        raise SmokeSequenceError(
            "Sanitized evidence failed privacy checks.",
            {
                "leakCount": len(leaks),
                "firstLeak": leaks[0],
                "privacy": "leak_paths_only_no_secret_values",
            },
        )


def find_shareable_evidence_leaks(value: Any, path: str = "$") -> list[dict[str, str]]:
    leaks: list[dict[str, str]] = []
    forbidden_keys = {"jobId", "uploadId", "sourceObjectKey", "uploadUrl", "sourcePath", "statePath", "uploadHeaders"}
    forbidden_value_fragments = (
        "X-Amz-",
        "Signature=",
        "Credential=",
        "uploads/",
        "/Users/",
        "/private/",
        "/var/folders/",
        "file://",
    )

    if isinstance(value, dict):
        for key, item in value.items():
            child_path = f"{path}.{key}"
            if key in forbidden_keys:
                leaks.append({"path": child_path, "reason": "forbidden_key"})
            leaks.extend(find_shareable_evidence_leaks(item, child_path))
    elif isinstance(value, list):
        for index, item in enumerate(value):
            leaks.extend(find_shareable_evidence_leaks(item, f"{path}[{index}]"))
    elif isinstance(value, str):
        for fragment in forbidden_value_fragments:
            if fragment in value:
                leaks.append({"path": path, "reason": f"forbidden_fragment:{fragment}"})
                break
    return leaks


def summarize_text(value: str) -> str:
    compact = " ".join(value.split())
    return compact[:240] if compact else "none"


def stable_hash(value: str) -> str:
    return hashlib.sha256(value.encode("utf-8")).hexdigest()[:16]


if __name__ == "__main__":
    raise SystemExit(main())
